# Generated by Django 4.1.1 on 2022-12-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя автора', max_length=100, verbose_name='name_auth')),
            ],
            options={
                'verbose_name': 'Author',
                'db_table': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название темы', max_length=100, verbose_name='name_theme')),
            ],
            options={
                'verbose_name': 'Theme',
                'db_table': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название новости', max_length=100, verbose_name='name_news')),
                ('description', models.TextField(blank=True, help_text='Описание новости', max_length=1000, null=True, verbose_name='descr')),
                ('author', models.ForeignKey(help_text='ID автора', on_delete=django.db.models.deletion.CASCADE, to='forum.authors')),
                ('theme', models.ForeignKey(help_text='ID темы', on_delete=django.db.models.deletion.CASCADE, to='forum.themes', verbose_name='theme')),
            ],
            options={
                'verbose_name': 'News',
                'db_table': 'News',
            },
        ),
    ]
